app:
  image:
    bucket: C:\Users\Georgy\IdeaProjects\CinemaChain\images
spring:
  jpa:
    open-in-view: false
    properties.hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
