--liquibase formatted sql

--changeset gman97:1
CREATE TABLE cinemas (
    id SERIAL PRIMARY KEY ,
    name VARCHAR(64) NOT NULL UNIQUE
);

--changeset gman97:2
CREATE TABLE cinema_halls (
    id SERIAL PRIMARY KEY ,
    number INTEGER NOT NULL ,
    size VARCHAR(32) NOT NULL ,
    cinema_id INTEGER REFERENCES cinemas(id)
);

--changeset gman97:3
CREATE TABLE movies (
    id SERIAL PRIMARY KEY ,
    title VARCHAR(32) NOT NULL ,
    premiere DATE NOT NULL ,
    rent_end DATE NOT NULL ,
    duration VARCHAR(16) NOT NULL ,
    pegi VARCHAR(16) NOT NULL ,
    description TEXT NOT NULL
);

--changeset gman97:4
CREATE TABLE film_sessions (
    id BIGSERIAL PRIMARY KEY ,
    begin_session TIMESTAMP NOT NULL ,
    movie_id INTEGER REFERENCES movies(id) ,
    cinema_hall_id INTEGER REFERENCES cinema_halls(id)
);

--changeset gman97:5
CREATE TABLE tickets (
    id BIGSERIAL PRIMARY KEY ,
    movie_title VARCHAR(32) NOT NULL ,
    movie_duration VARCHAR(16) NOT NULL ,
    begin_session TIMESTAMP NOT NULL ,
    cinema_name VARCHAR(64) NOT NULL ,
    hall_number INTEGER NOT NULL ,
    row SMALLINT NOT NULL ,
    seat_no SMALLINT NOT NULL ,
    cost NUMERIC(6, 2) NOT NULL ,
    film_session_id BIGINT REFERENCES film_sessions(id)
);

--changeset gman97:6
CREATE TABLE hall_seats (
    id SMALLSERIAL PRIMARY KEY ,
    row SMALLINT NOT NULL ,
    seat_no SMALLINT NOT NULL ,
    small_hall_seat_exists BOOLEAN NOT NULL ,
    middle_hall_seat_exists BOOLEAN NOT NULL ,
    big_hall_seat_exists BOOLEAN NOT NULL
);

--changeset gman97:7
INSERT INTO hall_seats (row, seat_no, small_hall_seat_exists, middle_hall_seat_exists, big_hall_seat_exists)
VALUES

    (1, 1, true, true, true),
    (1, 2, true, true, true),
    (1, 3, true, true, true),
    (1, 4, true, true, true),
    (1, 5, true, true, true),
    (1, 6, true, true, true),
    (1, 7, true, true, true),
    (1, 8, true, true, true),
    (1, 9, true, true, true),
    (1, 10, true, true, true),
    (1, 11, true, true, true),
    (1, 12, true, true, true),
    (1, 13, true, true, true),
    (1, 14, true, true, true),
    (1, 15, true, false, true),
    (1, 16, true, false, true),

    (1, 17, false, false, true),
    (1, 18, false, false, true),
    (1, 19, false, false, true),
    (1, 20, false, false, true),
    (1, 21, false, false, true),
    (1, 22, false, false, true),
    (1, 23, false, false, true),
    (1, 24, false, false, true),
    (1, 25, false, false, true),
    (1, 26, false, false, true),
    (1, 27, false, false, true),


    (2, 1, true, true, true),
    (2, 2, true, true, true),
    (2, 3, true, true, true),
    (2, 4, true, true, true),
    (2, 5, true, true, true),
    (2, 6, true, true, true),
    (2, 7, true, true, true),
    (2, 8, true, true, true),
    (2, 9, true, true, true),
    (2, 10, true, true, true),
    (2, 11, true, true, true),
    (2, 12, true, true, true),
    (2, 13, true, true, true),
    (2, 14, true, true, true),
    (2, 15, true, true, true),
    (2, 16, true, true, true),

    (2, 17, false, false, true),
    (2, 18, false, false, true),
    (2, 19, false, false, true),
    (2, 20, false, false, true),
    (2, 21, false, false, true),
    (2, 22, false, false, true),
    (2, 23, false, false, true),
    (2, 24, false, false, true),
    (2, 25, false, false, true),
    (2, 26, false, false, true),
    (2, 27, false, false, true),


    (3, 1, true, true, true),
    (3, 2, true, true, true),
    (3, 3, true, true, true),
    (3, 4, true, true, true),
    (3, 5, true, true, true),
    (3, 6, true, true, true),
    (3, 7, true, true, true),
    (3, 8, true, true, true),
    (3, 9, true, true, true),
    (3, 10, true, true, true),
    (3, 11, true, true, true),
    (3, 12, true, true, true),
    (3, 13, true, true, true),
    (3, 14, true, true, true),
    (3, 15, true, true, true),
    (3, 16, true, true, true),

    (3, 17, false, false, true),
    (3, 18, false, false, true),
    (3, 19, false, false, true),
    (3, 20, false, false, true),
    (3, 21, false, false, true),
    (3, 22, false, false, true),
    (3, 23, false, false, true),
    (3, 24, false, false, true),
    (3, 25, false, false, true),
    (3, 26, false, false, true),
    (3, 27, false, false, true),


    (4, 1, true, true, true),
    (4, 2, true, true, true),
    (4, 3, true, true, true),
    (4, 4, true, true, true),
    (4, 5, true, true, true),
    (4, 6, true, true, true),
    (4, 7, true, true, true),
    (4, 8, true, true, true),
    (4, 9, true, true, true),
    (4, 10, true, true, true),
    (4, 11, true, true, true),
    (4, 12, true, true, true),
    (4, 13, false, true, true),
    (4, 14, false, true, true),
    (4, 15, false, true, true),
    (4, 16, false, true, true),

    (4, 17, false, false, true),
    (4, 18, false, false, true),
    (4, 19, false, false, true),
    (4, 20, false, false, true),
    (4, 21, false, false, true),
    (4, 22, false, false, true),
    (4, 23, false, false, true),
    (4, 24, false, false, true),
    (4, 25, false, false, true),
    (4, 26, false, false, true),
    (4, 27, false, false, true),


    (5, 1, true, true, true),
    (5, 2, true, true, true),
    (5, 3, true, true, true),
    (5, 4, true, true, true),
    (5, 5, true, true, true),
    (5, 6, true, true, true),
    (5, 7, true, true, true),
    (5, 8, true, true, true),
    (5, 9, true, true, true),
    (5, 10, true, true, true),
    (5, 11, true, true, true),
    (5, 12, true, true, true),
    (5, 13, false, true, true),
    (5, 14, false, true, true),
    (5, 15, false, true, true),
    (5, 16, false, true, true),

    (5, 17, false, false, true),
    (5, 18, false, false, true),
    (5, 19, false, false, true),
    (5, 20, false, false, true),
    (5, 21, false, false, true),
    (5, 22, false, false, true),
    (5, 23, false, false, true),
    (5, 24, false, false, true),
    (5, 25, false, false, true),
    (5, 26, false, false, true),
    (5, 27, false, false, true),


    (6, 1, true, true, true),
    (6, 2, true, true, true),
    (6, 3, true, true, true),
    (6, 4, true, true, true),
    (6, 5, true, true, true),
    (6, 6, true, true, true),
    (6, 7, true, true, true),
    (6, 8, true, true, true),
    (6, 9, true, true, true),
    (6, 10, true, true, true),
    (6, 11, true, true, true),
    (6, 12, true, true, true),
    (6, 13, false, true, true),
    (6, 14, false, true, true),
    (6, 15, false, true, true),
    (6, 16, false, true, true),

    (6, 17, false, false, true),
    (6, 18, false, false, true),
    (6, 19, false, false, true),
    (6, 20, false, false, true),
    (6, 21, false, false, true),
    (6, 22, false, false, true),
    (6, 23, false, false, true),
    (6, 24, false, false, true),
    (6, 25, false, false, true),
    (6, 26, false, false, true),
    (6, 27, false, false, true),


    (7, 1, true, true, true),
    (7, 2, true, true, true),
    (7, 3, true, true, true),
    (7, 4, true, true, true),
    (7, 5, true, true, true),
    (7, 6, true, true, true),
    (7, 7, true, true, true),
    (7, 8, true, true, true),
    (7, 9, true, true, true),
    (7, 10, true, true, true),
    (7, 11, true, true, true),
    (7, 12, true, true, true),
    (7, 13, false, true, true),
    (7, 14, false, true, true),
    (7, 15, false, true, true),
    (7, 16, false, true, true),

    (7, 17, false, false, true),
    (7, 18, false, false, true),
    (7, 19, false, false, true),
    (7, 20, false, false, true),
    (7, 21, false, false, true),
    (7, 22, false, false, true),
    (7, 23, false, false, true),
    (7, 24, false, false, true),
    (7, 25, false, false, true),
    (7, 26, false, false, true),
    (7, 27, false, false, true),


    (8, 1, false, true, true),
    (8, 2, false, true, true),
    (8, 3, false, true, true),
    (8, 4, false, true, true),
    (8, 5, false, true, true),
    (8, 6, false, true, true),
    (8, 7, false, true, true),
    (8, 8, false, true, true),
    (8, 9, false, true, true),
    (8, 10, false, true, true),
    (8, 11, false, true, true),
    (8, 12, false, true, true),
    (8, 13, false, true, true),
    (8, 14, false, true, true),
    (8, 15, false, true, true),
    (8, 16, false, true, true),

    (8, 17, false, false, true),
    (8, 18, false, false, true),
    (8, 19, false, false, true),
    (8, 20, false, false, true),
    (8, 21, false, false, true),
    (8, 22, false, false, true),
    (8, 23, false, false, true),
    (8, 24, false, false, true),
    (8, 25, false, false, true),


    (9, 1, false, true, true),
    (9, 2, false, true, true),
    (9, 3, false, true, true),
    (9, 4, false, true, true),
    (9, 5, false, true, true),
    (9, 6, false, true, true),
    (9, 7, false, true, true),
    (9, 8, false, true, true),
    (9, 9, false, true, true),
    (9, 10, false, true, true),
    (9, 11, false, true, true),
    (9, 12, false, true, true),
    (9, 13, false, true, true),
    (9, 14, false, true, true),
    (9, 15, false, false, true),
    (9, 16, false, false, true),

    (9, 17, false, false, true),
    (9, 18, false, false, true),
    (9, 19, false, false, true),
    (9, 20, false, false, true),
    (9, 21, false, false, true),
    (9, 22, false, false, true),
    (9, 23, false, false, true),
    (9, 24, false, false, true),
    (9, 25, false, false, true),


    (10, 1, false, true, true),
    (10, 2, false, true, true),
    (10, 3, false, true, true),
    (10, 4, false, true, true),
    (10, 5, false, true, true),
    (10, 6, false, true, true),
    (10, 7, false, true, true),
    (10, 8, false, true, true),
    (10, 9, false, true, true),
    (10, 10, false, true, true),
    (10, 11, false, true, true),
    (10, 12, false, true, true),
    (10, 13, false, true, true),
    (10, 14, false, true, true),
    (10, 15, false, false, true),
    (10, 16, false, false, true),

    (10, 17, false, false, true),
    (10, 18, false, false, true),
    (10, 19, false, false, true),
    (10, 20, false, false, true),
    (10, 21, false, false, true),
    (10, 22, false, false, true),
    (10, 23, false, false, true),
    (10, 24, false, false, true),
    (10, 25, false, false, true),


    (11, 1, false, true, true),
    (11, 2, false, true, true),
    (11, 3, false, true, true),
    (11, 4, false, true, true),
    (11, 5, false, true, true),
    (11, 6, false, true, true),
    (11, 7, false, true, true),
    (11, 8, false, true, true),
    (11, 9, false, true, true),
    (11, 10, false, true, true),
    (11, 11, false, true, true),
    (11, 12, false, true, true),
    (11, 13, false, true, true),
    (11, 14, false, true, true),
    (11, 15, false, false, true),
    (11, 16, false, false, true),

    (11, 17, false, false, true),
    (11, 18, false, false, true),
    (11, 19, false, false, true),
    (11, 20, false, false, true),
    (11, 21, false, false, true),
    (11, 22, false, false, true),
    (11, 23, false, false, true),
    (11, 24, false, false, true),
    (11, 25, false, false, true),


    (12, 1, false, false, true),
    (12, 2, false, false, true),
    (12, 3, false, false, true),
    (12, 4, false, false, true),
    (12, 5, false, false, true),
    (12, 6, false, false, true),
    (12, 7, false, false, true),
    (12, 8, false, false, true),
    (12, 9, false, false, true),
    (12, 10, false, false, true),
    (12, 11, false, false, true),
    (12, 12, false, false, true),
    (12, 13, false, false, true),
    (12, 14, false, false, true),
    (12, 15, false, false, true),
    (12, 16, false, false, true),

    (12, 17, false, false, true),
    (12, 18, false, false, true),
    (12, 19, false, false, true),
    (12, 20, false, false, true),
    (12, 21, false, false, true),
    (12, 22, false, false, true),
    (12, 23, false, false, true),
    (12, 24, false, false, true),
    (12, 25, false, false, true),


    (13, 1, false, false, true),
    (13, 2, false, false, true),
    (13, 3, false, false, true),
    (13, 4, false, false, true),
    (13, 5, false, false, true),
    (13, 6, false, false, true),
    (13, 7, false, false, true),
    (13, 8, false, false, true),
    (13, 9, false, false, true),
    (13, 10, false, false, true),
    (13, 11, false, false, true),
    (13, 12, false, false, true),
    (13, 13, false, false, true),
    (13, 14, false, false, true);


